// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	OrganizerID  int64          `json:"organizer_id"`
	Price        int32          `json:"price"`
	Amount       int32          `json:"amount"`
	AmountSold   int32          `json:"amount_sold"`
	Description  sql.NullString `json:"description"`
	IsClosed     bool           `json:"is_closed"`
	AmountRedeem int32          `json:"amount_redeem"`
	StartTime    time.Time      `json:"start_time"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Order struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	EventID   int64          `json:"event_id"`
	Amount    int32          `json:"amount"`
	SumPrice  int32          `json:"sum_price"`
	Payment   sql.NullString `json:"payment"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Organizer struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Phone    sql.NullString `json:"phone"`
}

type Ticket struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	EventID    int64          `json:"event_id"`
	OrderID    int64          `json:"order_id"`
	IsRedeemed sql.NullBool   `json:"is_redeemed"`
	Hashed     sql.NullString `json:"hashed"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type User struct {
	ID          int64        `json:"id"`
	UserID      string       `json:"user_id"`
	Email       string       `json:"email"`
	DisplayName string       `json:"display_name"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
